apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-recommendation
spec:
  replicas: 1
  selector:
    matchLabels:
      app: book-recommendation
  template:
    metadata:
      labels:
        app: book-recommendation
    spec:
      containers:
        - name: book-recommendation
          image: 2023sl93054/book-recommendation:latest
          ports:
            - containerPort: 8501
          livenessProbe:
            httpGet:
              path: /_stcore/health
              port: 8501
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /_stcore/health
              port: 8501
            initialDelaySeconds: 30
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: book-recommendation-service
spec:
  selector:
    app: book-recommendation
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8501
  type: LoadBalancer
